# 日志配置
logging:
  level:
    top.lctr.naive.file.system: warn
    org.springframework: warn

#文件服务配置
file:
  #ffmpeg程序文件路径
  ffmpegFilePath: tools\ffmpeg\ffmpeg.exe
  #ffmpeg程序文件路径
  ffprobeFilePath: tools\ffmpeg\ffprobe.exe
  #ffplay程序文件路径
  ffplayFilePath: tools\ffmpeg\ffplay.exe